@startuml v1 infra
node client{
  component Redux
  component React
  component Socket_io_client
}

node serveur{
  component socket_io_serveur
  component koa
  component DiscordJs
  component Koa_Static_client
  component Store
  component Db
}

koa <--> socket_io_serveur
koa <--> DiscordJs
koa <--> Store
koa <--> Db
koa <--> Koa_Static_client
Db <--> Store
Db <--> DiscordJs
socket_io_serveur <--> DiscordJs
socket_io_serveur <--> Store
socket_io_serveur <--> Db

client --> serveur : Axios
serveur --> client : Socket.io

@enduml